#cloud-config
users:
  - name: ubuntu
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAmyQ0****KyLb9VXTo5+a8zf0ytpKu8pXKYCQhB7vU+L1UVFO3UOO8WpRfDw== alexlinux@compute-vm-2-1-10-hdd-1764726993335
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
