---
- name: Setup sudo without password for ubuntu user
  hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Ensure sudoers.d directory exists
      file:
        path: /etc/sudoers.d
        state: directory
        mode: '0750'
    - name: Add ubuntu user to sudoers without password
      copy:
        content: "ubuntu ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/ubuntu
        mode: '0440'
