---
- name: Install ClickHouse
  hosts: clickhouse
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install ClickHouse packages
      ansible.builtin.apt:
        name:
          - clickhouse-server
          - clickhouse-client
        state: present

- name: Install Vector
  hosts: vector
  become: true

  tasks:
    - name: Download Vector package
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.28.0/vector_0.28.0-1_amd64.deb"
        dest: "/tmp/vector.deb"
        mode: '0644'
        timeout: 30

    - name: Install Vector
      ansible.builtin.apt:
        deb: "/tmp/vector.deb"
        state: present

- name: Install Lighthouse with Nginx
  hosts: lighthouse
  become: true

  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Clone Lighthouse repository
      ansible.builtin.git:
        repo: "https://github.com/VKCOM/lighthouse"
        dest: "/var/www/lighthouse"
        version: "master"  # Фиксируем версию

    - name: Configure Nginx for Lighthouse
      ansible.builtin.template:
        src: "templates/lighthouse-nginx.conf.j2"
        dest: "/etc/nginx/sites-available/lighthouse"
        mode: '0644'
        owner: root
        group: root

    - name: Enable Lighthouse site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/lighthouse
        dest: /etc/nginx/sites-enabled/lighthouse
        state: link

    - name: Disable default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Start Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
